# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2


_PAKIET_TYPE = descriptor.EnumDescriptor(
  name='Type',
  full_name='datapakiet.pakiet.Type',
  filename='Type',
  values=[
    descriptor.EnumValueDescriptor(
      name='PING', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='COMMAND', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='FTPDOWNLOAD', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='EXIT', index=3, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='BUILD', index=4, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RUNTESTS', index=5, number=5,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GETRESULTS', index=6, number=6,
      options=None,
      type=None),
  ],
  options=None,
)


_PAKIET = descriptor.Descriptor(
  name='pakiet',
  full_name='datapakiet.pakiet',
  filename='datapakiet.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='typ', full_name='datapakiet.pakiet.typ', index=0,
      number=1, type=14, cpp_type=8, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='msg', full_name='datapakiet.pakiet.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='port', full_name='datapakiet.pakiet.port', index=2,
      number=3, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
    _PAKIET_TYPE,
  ],
  options=None)


_PAKIET.fields_by_name['typ'].enum_type = _PAKIET_TYPE

class pakiet(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PAKIET

